-- Pobación por ciudades principales (Natural Earth + INE Padrón 2023)
-- Círculos de 15km por ciudad, población área metropolitana
-- Ejecutar en Supabase → SQL Editor

DELETE FROM census_sections;

INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_madrid', 'Madrid', NULL, 'Comunidad de Madrid', NULL, 5567000, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-3.685297, 40.401972), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_barcelona', 'Barcelona', NULL, 'Cataluña', NULL, 4920000, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(2.181424, 41.385245), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_seville', 'Seville', NULL, 'Andalucía', NULL, 1212045, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-5.980007, 37.405015), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_bilbao', 'Bilbao', NULL, 'País Vasco', NULL, 875552, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-2.929987, 43.249981), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_valencia', 'Valencia', NULL, 'Comunidad Valenciana', NULL, 808000, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-0.401958, 39.486963), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_zaragoza', 'Zaragoza', NULL, 'Aragón', NULL, 649404, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-0.889982, 41.650002), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_málaga', 'Málaga', NULL, 'Andalucía', NULL, 550058, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-4.419999, 36.720406), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_murcia', 'Murcia', NULL, 'Región de Murcia', NULL, 406807, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-1.129968, 37.979993), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_granada‎', 'Granada‎', NULL, 'Andalucía', NULL, 388290, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-3.585011, 37.164978), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_vigo', 'Vigo', NULL, 'Galicia', NULL, 378952, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-8.729995, 42.220019), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_las_palmas', 'Las Palmas', NULL, 'None', NULL, 378495, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-15.429999, 28.099976), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_palma', 'Palma', NULL, 'Islas Baleares', NULL, 375773, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(2.654246, 39.574263), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_la_coruña', 'La Coruña', NULL, 'Galicia', NULL, 370610, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-8.419988, 43.329977), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_san_sebastián', 'San Sebastián', NULL, 'País Vasco', NULL, 357468, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-1.979993, 43.320391), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_santa_cruz_de_teneri', 'Santa Cruz de Tenerife', NULL, 'None', NULL, 336061, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-16.250001, 28.469979), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_gijón', 'Gijón', NULL, 'Principado de Asturias', NULL, 335972, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-5.67, 43.530016), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_valladolid', 'Valladolid', NULL, 'Castilla y León', NULL, 322304, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-4.750031, 41.650002), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_córdoba', 'Córdoba', NULL, 'Andalucía', NULL, 321376, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-4.770004, 37.879999), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_alicante', 'Alicante', NULL, 'Comunidad Valenciana', NULL, 315863, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-0.483641, 38.35122), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_cádiz', 'Cádiz', NULL, 'Andalucía', NULL, 283157, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-6.286141, 36.524829), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_pamplona', 'Pamplona', NULL, 'Comunidad Foral de Navarra', NULL, 274545, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-1.649987, 42.820008), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_oviedo', 'Oviedo', NULL, 'Principado de Asturias', NULL, 235651, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-5.829991, 43.350492), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_vitoria', 'Vitoria', NULL, 'País Vasco', NULL, 224578, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-2.669977, 42.84998), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_santander', 'Santander', NULL, 'Cantabria', NULL, 208763, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-3.799985, 43.380465), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_cartagena', 'Cartagena', NULL, 'Región de Murcia', NULL, 201274, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-0.980028, 37.60043), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_marbella', 'Marbella', NULL, 'Andalucía', NULL, 186131, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-4.88333, 36.51662), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_mataró', 'Mataró', NULL, 'Cataluña', NULL, 183293, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(2.450021, 41.539957), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_castello', 'Castello', NULL, 'Comunidad Valenciana', NULL, 180610, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-0.050008, 39.970414), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_almería', 'Almería', NULL, 'Andalucía', NULL, 179405, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-2.429991, 36.830348), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_burgos', 'Burgos', NULL, 'Castilla y León', NULL, 170183, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-3.679967, 42.350398), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_salamanca', 'Salamanca', NULL, 'Castilla y León', NULL, 162353, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-5.67, 40.970405), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_albacete', 'Albacete', NULL, 'Castilla-La Mancha', NULL, 158094, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-1.87, 39.000344), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_huelva', 'Huelva', NULL, 'Andalucía', NULL, 144174, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-6.929949, 37.250374), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_logroño', 'Logroño', NULL, 'La Rioja', NULL, 143698, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-2.429991, 42.470365), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_melilla', 'Melilla', NULL, 'Melilla', NULL, 141308, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-2.950011, 35.300002), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_badajoz', 'Badajoz', NULL, 'Extremadura', NULL, 140133, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-6.969973, 38.880429), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_león', 'León', NULL, 'Castilla y León', NULL, 136227, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-5.570007, 42.579971), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_tarragona', 'Tarragona', NULL, 'Cataluña', NULL, 126291, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(1.249991, 41.12037), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_ourense', 'Ourense', NULL, 'Galicia', NULL, 118107, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-7.869995, 42.32996), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_jaén', 'Jaén', NULL, 'Andalucía', NULL, 116400, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-3.799985, 37.770393), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_algeciras', 'Algeciras', NULL, 'Andalucía', NULL, 111027, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-5.45266, 36.131882), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_santiago_de_composte', 'Santiago de Compostela', NULL, 'Galicia', NULL, 92430, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-8.541091, 42.882898), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_lorca', 'Lorca', NULL, 'Región de Murcia', NULL, 86119, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-1.698512, 37.688564), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_ceuta', 'Ceuta', NULL, 'Ceuta', NULL, 78674, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-5.306999, 35.888984), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_toledo', 'Toledo', NULL, 'Castilla-La Mancha', NULL, 74632, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-4.016716, 39.867036), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_guadalajara', 'Guadalajara', NULL, 'Castilla-La Mancha', NULL, 72850, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-3.166587, 40.633707), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_linares', 'Linares', NULL, 'Andalucía', NULL, 59761, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-3.633355, 38.08332), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_arrecife', 'Arrecife', NULL, 'None', NULL, 52944, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-13.537833, 28.969049), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;
INSERT INTO census_sections (cusec, municipality, municipality_code, province, province_code, population, area_km2, geometry) VALUES ('city_mérida', 'Mérida', NULL, 'Extremadura', NULL, 52423, ROUND(CAST(pi() * 15 * 15 AS numeric), 2)::float, ST_Multi(ST_Buffer(  ST_SetSRID(ST_MakePoint(-6.337998, 38.912004), 4326)::geography, 15000)::geometry)) ON CONFLICT (cusec) DO UPDATE SET population=EXCLUDED.population, geometry=EXCLUDED.geometry;

SELECT COUNT(*) as ciudades, SUM(population) as poblacion_total FROM census_sections;