/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSeedRouteImport } from './routes/admin/seed'
import { Route as AdminPlaytomicRouteImport } from './routes/admin/playtomic'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaytomicRoute = AdminPlaytomicRouteImport.update({
  id: '/playtomic',
  path: '/playtomic',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/seed': typeof AdminSeedRoute
  '/admin/playtomic': typeof AdminPlaytomicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/seed': typeof AdminSeedRoute
  '/admin/playtomic': typeof AdminPlaytomicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/seed': typeof AdminSeedRoute
  '/admin/playtomic': typeof AdminPlaytomicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin/seed' | '/admin/playtomic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/seed' | '/admin/playtomic'
  id: '__root__' | '/' | '/admin' | '/admin/seed' | '/admin/playtomic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seed': {
      id: '/admin/seed'
      path: '/seed'
      fullPath: '/admin/seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/playtomic': {
      id: '/admin/playtomic'
      path: '/playtomic'
      fullPath: '/admin/playtomic'
      preLoaderRoute: typeof AdminPlaytomicRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSeedRoute: typeof AdminSeedRoute
  AdminPlaytomicRoute: typeof AdminPlaytomicRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSeedRoute: AdminSeedRoute,
  AdminPlaytomicRoute: AdminPlaytomicRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
